#!/usr/bin/env bash

setup_whiptail

TOKEN_USERNAME=$(whiptail --inputbox "What is the username?" $BOX_HEIGHT $BOX_WIDTH $LASTPASS_KEY_NAME --title "Create Basic Auth Token" 3>&1 1>&2 2>&3)
TOKEN_PASSWORD=$(whiptail --passwordbox "What is the password?" $BOX_HEIGHT $BOX_WIDTH $LASTPASS_KEY_NAME --title "Create Basic Auth Token" 3>&1 1>&2 2>&3)

TOKEN=$(echo -n "${TOKEN_USERNAME}:${TOKEN_PASSWORD}" | base64)

if $(whiptail --yesno "Your token is: '$TOKEN'. Do you want to copy it to your clipboard?" $BOX_HEIGHT $BOX_WIDTH --title "Create Basic Auth Token" 3>&1 1>&2 2>&3);
then
    echo -n "Basic $TOKEN" | pbcopy
    echo "Basic auth token copied to clipboard"
fi
