#!/usr/bin/env zsh

echo "Create Basic Auth Token"
echo ""

read "TOKEN_USERNAME?What is the username? "
read -s "TOKEN_PASSWORD?What is the password? "
echo ""

TOKEN=$(echo -n "${TOKEN_USERNAME}:${TOKEN_PASSWORD}" | base64)

echo ""
read -k "REPLY?Your token is: '$TOKEN'. Do you want to copy it to your clipboard? (y/n) "
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo -n "$TOKEN" | pbcopy
    echo "Basic auth token copied to clipboard"
fi
