#!/usr/bin/env bash

# If ~/.npmrc exists, move it to ~/.npmrc.bak. If it doesn't move ~/.npmrc.bak to ~/.npmrc.
if [ -f ~/.npmrc ]; then
    mv ~/.npmrc ~/.npmrc.bak
    echo "npmrc has been backed up"
else
    mv ~/.npmrc.bak ~/.npmrc
    echo "npmrc has been restored"
fi
