#!/usr/bin/env bash

# If $HOME/.npmrc exists, move it to $HOME/.npmrc.bak. If it doesn't move $HOME/.npmrc.bak to $HOME/.npmrc.
if [ -f $HOME/.npmrc ]; then
    mv $HOME/.npmrc $HOME/.npmrc.bak
    echo "npmrc has been backed up"
else
    mv $HOME/.npmrc.bak $HOME/.npmrc
    echo "npmrc has been restored"
fi
