#!/bin/bash
LASTPASS_EMAIL='nstanley@bandwidth.com'
PROFILE=$(clippy aws sso assume)
if [ $? -eq 0 ]
then
    export AWS_PROFILE=$PROFILE
    export AWS_DEFAULT_PROFILE=$PROFILE
    export AWS_EB_PROFILE=$PROFILE

    SSO_ACCOUNT=$(aws sts get-caller-identity --query "Account" --output text)
    if [ ${#SSO_ACCOUNT} -eq 12 ];  then
        echo "AWS SSO session valid" ;
    else
        echo "AWS SSO session invalid"
        aws sso login
    fi
fi