brew_installable=(
    "alfred"
    "eza"
    "iterm2"
    "google-chrome"
    "rectangle"
    "spotify"
    "monitorcontrol"
    "tlrc"
    "diff-so-fancy"
    "bat"
    "fzf"
    "volta"
    "lastpass-cli"
    "lazydocker"
    "lazygit"
    "slack"
    "htop"
    "session-manager-plugin"
    "terraform"
    "jq"
    "macmediakeyforwarder"
    "pyenv"
#   "gping"
#   "pure"
    "starship"
    "font-hack-nerd-font"
)
